services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: familyzen-api:latest
    container_name: familyzen-api
    environment:
      PORT: "8000"
      NODE_ENV: "production"
    ports:
      - "8000:8000"
      - "80:8000"       # pour accéder sans :8000
    restart: unless-stopped
    # healthcheck possible si tu veux :
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 12
    #   start_period: 20s
