version: "3.9"

services:
  api:
    build:
      context: .              # <-- fix: PAS ./backend
      dockerfile: Dockerfile  # adapte si le nom est différent
    image: familyzen-api:latest
    container_name: familyzen-api
    ports:
      - "8000:8000"
      - "80:8000"             # utile si tu exposes aussi sur 80
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
