# 4) Health check: jusqu’à 2 min (accepte JSON ou texte "ok")
- name: Health check
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.VM_HOST }}
    username: ${{ secrets.VM_USER }}
    key: ${{ secrets.VM_SSH_KEY }}
    script: |
      set -euo pipefail
      end=$((SECONDS+120))
      ok=false
      while [ $SECONDS -lt $end ]; do
        code=$(curl -fsS -o /tmp/health.out -w "%{http_code}" http://localhost:8000/health || echo 000)
        body=$(cat /tmp/health.out 2>/dev/null || true)
        echo "Health code=$code body='$body'"
        if [ "$code" = "200" ] && (echo "$body" | grep -qi '"ok"[[:space:]]*:[[:space:]]*true' || echo "$body" | grep -qi '\bok\b'); then
          ok=true
          break
        fi
        sleep 2
      done

      if [ "$ok" != true ]; then
        echo 'Health KO — logs docker ci-dessous:'
        cd /opt/familyzen
        sudo docker compose logs --tail 200 || true
        exit 1
      fi

      echo 'Health OK'
